# Promtheus Monitoring config example
#
#

global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'example_app'
    metrics_path: '/_status/vars'
    scheme: 'https'
    tls_config:
        insecure_skip_verify: true

    static_configs:
        
    - targets: ['localhost:8082', 'localhost:8083']
      labels:
        cluster: 'dev-cluster'
